# This is the recommended way of running Baserow using docker-compose for most users.
# See https://baserow.io/docs/installation%2Finstall-with-docker for more details.
version: "3.4"
services:
  baserow:
    container_name: baserow
    image: baserow/baserow:1.33.4
    labels:
      - io.containers.autoupdate=registry
      - traefik.enable=true
      - traefik.http.routers.baserow.rule=Host(`baserow.africanlocalnetwork.com`) 
      - traefik.http.routers.baserow.entrypoints=websecure
      - traefik.http.routers.baserow.tls=true
    environment:
      BASEROW_PUBLIC_URL: 'https://baserow.africanlocalnetwork.com'
    ports:
      - "8081:80"
      - "4443:443"
    volumes:
      - baserow_data:/baserow/data
    networks:
      - n8nnet
volumes:
  baserow_data:
networks:
  n8nnet:
    driver: bridge

